[package]
name = "crosstown_bus"
version = "0.8.1"
edition = "2021"
authors = ["paoloposso <pvictorsys@gmail.com>"]
readme = "README.md"
repository = "https://github.com/paoloposso/crosstown_bus"
description = "Event Bus with RabbitMQ for Rust"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = "0.4.0"
futures = "0.3"
borsh = "0.9.3"
borsh-derive = "0.9.1"
tokio = {version="1.21.2", features=["full"]}