version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"  # You can specify a specific version if needed
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
