name: Rust CI/CD

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Build project
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Publish to Cargo
        if: github.event.pull_request.merged == true
        env:
          CARGO_AUTH_TOKEN: ${{ secrets.CARGO_AUTH_TOKEN }}
        run: cargo login $CARGO_AUTH_TOKEN && cargo publish