name: Release Workflow

on:
  release:
    types:
        - published

jobs:
    release-job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup | Rust
              uses: ATiltedTree/setup-rust@v1
              with:
                rust-version: stable

            - name: Build and publish crate to crates.io
              run: |
                # Authenticate with crates.io using your API token
                echo "//registry.npmjs.org/:_authToken=${{ secrets.CRATES_IO_TOKEN }}" > ~/.cargo/credentials

                # Build and publish the crate
                cargo publish --dry-run  # Use --dry-run for testing; remove it for actual publishing
      