name: Rust Tests

# on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Compose
        run: |
          docker-compose up -d

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup component add --toolchain stable rustfmt rust-src
          rustup default stable

      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Stop Docker Compose
        run: docker-compose down
